log_file_path: "/home/ekaterina/GitHub/Bash-Commands/log/log.txt"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s
postgres-attributes: "host=localhost user=postgres password=postgres dbname=commands port=5432 sslmode=disable"